accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]
      

pdfmr/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pdfmr"
urlpatterns = [
    path("home/", views.home, name="home"),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('list/', views.ListView.as_view(), name='list'),
    path('dell_file/', views.dell_file, name='dell_file'),
]

ptoe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pdfmr/', include('pdfmr.urls')),
    path('', include('accounts.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

pdfmr/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

pdfmr/forms.py
from django import forms
from django.conf import settings
from django.core.files.storage import default_storage
import os, random, string
from upload_validator import FileTypeValidator


class UploadForm(forms.Form):
    #PDFアップロード用フォームの定義
    document = forms.FileField(label="PDFアップロード",
        widget=forms.ClearableFileInput(attrs={'multiple': True}), 
        validators=[FileTypeValidator(allowed_types=[ 'application/pdf'])])
    
    #saveメソッドはアップロードしたPDFを一時フォルダに保存する。
    def save(self):
        upload_files = self.files.getlist('document')
        temp_dir = os.path.join(settings.MEDIA_ROOT, self.create_dir(10))   #一時フォルダの生成
        #アップロードされたPDFファイルを1件ずつ取得
        for pdf in upload_files:
            #default_strageはDjango標準で備わっているファイルオブジェクトを操作するためのメソッド
            #第一引数は保存先のパス。第二引数は保存するパス
            default_storage.save(os.path.join(temp_dir, pdf.name), pdf)   #一時フォルダにPDFを保存
        return temp_dir
    
    def create_dir(self, n):
        #一時フォルダ名生成するための関数
        return 'pdf\\' + ''.join(random.choices(string.ascii_letters + string.digits, k=n))

    

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm #forms.py のLOginForm


class Login(LoginView):
    #ログインページ
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    #ログアウトページ"
    template_name = 'accounts/login.html'

pdfmr/views.py
from django.shortcuts import render
from django.views import generic  
from django.contrib.auth.mixins import LoginRequiredMixin   # ログオンユーザのみアクセス可とするために利用する
from django.conf import settings  # settings.pyの定義内容を利用するため
from .forms import UploadForm   
from django.core.files.storage import default_storage   # ファイルオブジェクト操作のためdefault_storageを利用する
import shutil, os 
from .utils import create_excel
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, "pdfmr/home.html")


class UploadView(LoginRequiredMixin, generic.FormView):
    form_class = UploadForm
    template_name = 'pdfmr/upload_form.html'

#FormViewはWEB画面から受け取ったデータのバリデーション結果によって処理を分岐。form_validとform_invalid
    def form_valid(self, form):
        user_name = self.request.user.username  #ログオンユーザ名の取得
        user_dir = os.path.join(settings.MEDIA_ROOT, "excel", user_name)   #ユーザディレクトリパスの生成
        if not os.path.isdir(user_dir):  #ユーザディレクトリの作成
            os.makedirs(user_dir)
        temp_dir = form.save()  # upload一時フォルダの取得
        #PDF->Excelデータ生成
        err = create_excel(temp_dir, user_name)  #PDF->Excelデータ生成
        if err:
            shutil.rmtree(temp_dir)  #upload一時フォルダの削除
            context = {
                'err': err,
            }
            return render(self.request, 'pdfmr/complete.html', context)


    def form_invalid(self, form):
        return render(self.request, 'pdfmr/upload_form.html', {'form': form})


class ListView(LoginRequiredMixin, generic.TemplateView):
    
    template_name = 'pdfmr/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  
        #自分が作成したExcelファイルだけを一覧表示
        login_user_name = self.request.user.username
        if not default_storage.exists(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name)):
            warning_message = "一度もファイル作成が行われていません。"
            context = {
                'warning_message':warning_message,
                }
            return context
        file_list = default_storage.listdir(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name))[1]
        context = {
            'file_list': file_list,
            'login_user_name':login_user_name,
            }
        return context

@login_required    
def dell_file(request):
    #CheckBoxがOnのファイル名を取得
    checks_value = request.POST.getlist('checks')
    #ログオンユーザ名を取得
    login_user_name = request.user.username
    
    #Excelファイルの格納パスを取得
    if checks_value:
        for file in checks_value:
            path = os.path.join(settings.MEDIA_ROOT, "excel", login_user_name, file)
            #CheckBox=ONのファイルを削除
            default_storage.delete(path)
        return render(request, 'pdfmr/delete.html', {'checks_value': checks_value})
    else:
        login_user_name = request.user.username
        file_list = default_storage.listdir(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name))[1]
        warning_message = "削除するファイルが選択してください。"
        
        context = { 
            'file_list': file_list,
            'login_user_name':login_user_name,
            'warning_message': warning_message,
        }
        return render(request, 'pdfmr/list.html',context)

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PDFtoExcel</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/bower_components/Ionicons/css/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/dist/css/AdminLTE.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/iCheck/square/blue.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>PDFtoExcel</b>
    </div>
    <div class="login-box-body">
      <p class="login-box-msg"><b>ログイン</b></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
  <script src="{% static 'AdminLTE-3.0.5/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'AdminLTE-3.0.5/plugins/iCheck/icheck.min.js' %}"></script>
</body>
</html>

templates/pdfmr/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PDF2EXCEL</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/jqvmap/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE-3.0.5/plugins/summernote/summernote-bs4.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
        {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
        <li>
            <a class="nav-link">ユーザー名：{{ user.get_username }}</a>
        </li>
        <li>
            <a class="nav-link" href="{% url 'accounts:logout' %}">
                <i class="fa fa-fw fa-sign-out"></i>ログアウト
            </a>
        </li>
        {% endif %}
    </ul>
  </nav>

  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{% url 'pdfmr:home' %}" class="brand-link">
      <span class="brand-text font-weight-light">PDF2EXCEL</span>
    </a>

    <div class="sidebar">
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                PDFtoExcelメニュー
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'pdfmr:upload' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>PDFアップロード</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'pdfmr:list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Excel管理</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </aside>

  {% block content %}

  {% endblock %}


  <footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="http://adminlte.io">kosuketakei</a>.</strong>
    All rights reserved.
  </footer>

  <aside class="control-sidebar control-sidebar-dark">
  </aside>
</div>

<script src="{% static 'AdminLTE-3.0.5/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="{% static 'AdminLTE-3.0.5/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/sparklines/sparkline.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/dist/js/adminlte.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/dist/js/pages/dashboard.js' %}"></script>
<script src="{% static 'AdminLTE-3.0.5/dist/js/demo.js' %}"></script>
</body>
<script language="JavaScript" type="text/javascript">
    // 「全て選択」チェックで全てにチェック付く
       function AllChecked(){
         var all = document.form.all.checked;
         for (var i=0; i<document.form.checks.length; i++){
           document.form.checks[i].checked = all;
           }
           }
        // 一つでもチェックを外すと「全て選択」のチェック外れる
        function　DisChecked(){
          var checks = document.form.checks;
          var checksCount = 0;
          for (var i=0; i<checks.length; i++){
            if(checks[i].checked == false){
              document.form.all.checked = false;
            }else{
              checksCount += 1;
              if(checksCount == checks.length){
                document.form.all.checked = true;
              }
            }
          }
        }
    </script>
</html>

templates/pdfmr/complete.html
{% extends './base.html' %}
{% block content %}
<div class="content-wrapper">
<section class="content-header">
  <h1>一覧画面</h1>
</section>
<section class="content">
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title"> <b>PDF→Excel変換処理結果</b></h3>
      </div>
      <div class="box-body">
        <div class="card-body">
          {% if message  %}
          <div class="callout callout-info">
            {{message}}
          </div>
          {% endif %}
          {% if err  %}
        <div class="callout callout-danger">
          {{err |safe}}
        </div>
    {% endif %}
        </div>
        <hr>
        <div class="text-center">
          <a href="{% url 'pdfmr:home' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</section>

{% endblock content %}

templates/pdfmr/delete.html
{% extends './base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>Excelファイル削除完了</h1>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">選択した Excelファイル削除が完了しました。</h3>
          </div>
          <div class="box-body">
            <hr>
            <div class="card-body">
              <b> 削除したファイル一覧</b><br>
              <ul class="list-group">
                {% for file in  checks_value　%}
                <li class="list-group-item  alert alert-success alert-dismissible" role="alert">{{file}}</li>
                {% endfor %}
              </ul>
              <hr>
            </div>
            <div class="text-center">
              <a href="{% url 'pdfmr:home' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
              <a href="{% url 'pdfmr:list' %}" class="btn btn-primary btn-sm" role="button">一覧表示画面へ</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/pdfmr/home.html
  {% extends './base.html' %}
  {% block content %}

  <div class="content-wrapper">
    <section class="content-header">
        <h1>ファイル形式変換器</h1>
        <p>~PDF形式のファイルをExcel形式に変換~</p>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h4>PDF to Excel</h4>
                        <p>PDF→Excel変換</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-share"></i>
                    </div>
                    <a href="{% url 'pdfmr:upload' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h4>Excel管理画面</h4>
                        <p>生成済みExcelファイルの管理</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-document"></i>
                    </div>
                    <a href="{% url 'pdfmr:list' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <section class="col-lg-7 connectedSortable"></section>
        </div>
    </section>
  </div>
{% endblock content %}

templates/pdfmr/list.html
{% extends './base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="content-wrapper">
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"> <b>　生成したExcelファイル一覧</b></h3>
            <p></p>
          </div>
          <div class="box-body">
            <div class="card-body">
              <hr>
              <form action='{% url 'pdfmr:dell_file' %}' name="form" method="post"> 
                {% csrf_token %}
                <label>
                  <input type="checkbox" name="all" onClick="AllChecked();" />  全て選択
                </label><br>  
              {% for file in file_list %}
              <label>
                <input type="checkbox" name="checks" value="{{file}}"/>
                <a href="http://127.0.0.1:8000/media/excel/{{login_user_name}}/{{file}}">{{file}}</a>
              </label>
              <br> 
              {% endfor %}
              <input type="submit" id="button" name="button"  class="btn btn-sm btn-danger" value="削除">
            </form>
            {% if warning_message %}
            <hr>
            <div class="alert alert-warning alert-dismissible" role="alert">
              <p>{{warning_message}}</p>
            </div>
            {% endif %}
            <hr>
              <div class="text-center">
                <a href="{% url 'pdfmr:home' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

templates/pdfmr/upload_form.html
{% extends './base.html' %}
{% block content %}
<div class="content-wrapper">
<section class="content-header">
  <h1 class="box-title"><b>　PDF->Excel変換</b></h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
     
        </div>
        <div class="box-body">
          <hr>
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label class="col-lg-5 col-form-label"><h4>{{form.document.label}}</h4></label><br>
            <p>※PDFは複数ファイルを一括でアップロードできます。</p>
            <div class="form-group col-sm-5">
              {{form.document}}
            </div>
            <button type="submit" class="btn btn-sm btn-primary">アップロード</button>    
          </form>
          {% if form.errors %}<hr>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <p>PDF以外のファイルはアップロードできません。</p>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
</div>
{% endblock content %}